### ISSUE TITLE
Server crashing while starting

### ISSUE THREAD

**Issue by ShadowkillerGB** [Yeregorix/Mirage#50] opened 2022-10-30 11:00 UTC
My server is crashing while starting with the Mirage plugin installed.
The server runs on SpongeForge 1.12.2-2838-7.4.7 and has Mirage 1.4.0 installed.
I have the modpack "All the Mods 3 Lite" on the server.
Without Mirage the server is starting perfectly fine.
I also have a crash log if you need it:
[crash-2022-10-30_10.49.08-server.txt](https://github.com/Yeregorix/Mirage/files/9895648/crash-2022-10-30_10.49.08-server.txt)
Is the Mirage version just not compatible with the newest 1.12.2 SpongeForge version?
Let me know if you have found the problem

**Comment by Yeregorix** [comment] 2022-10-30 14:51
Duplicate of #11. A mod is conflicting with my plugin due to its id. I'm hosting jars with a different id at https://files.smoofyuniverse.net/smoofymirage/. Using them should fix your issue.

**Comment by ShadowkillerGB** [comment] 2022-10-31 08:59
Thanks! My server is starting now so the plugin should be installed.
For some reason I can't find the config folder of your plugin.
Do you hace any idea why?

**Comment by ShadowkillerGB** [comment] 2022-10-31 09:33
I tested it and the plugin seems to block my xray.
Still no config folder though

**Comment by Yeregorix** [comment] 2022-10-31 09:34
Configuration files should be `config/smoofymirage`.

**Comment by ShadowkillerGB** [comment] 2022-10-31 10:09
Oh, my bad. I looked for just mirage.
Well then everything works now!
Thank you for your help!
The plugin works really well now

**Closed** 2022-10-31 10:11 UTC
