### ISSUE TITLE
NPE when generating new chunks

### ISSUE THREAD

**Issue by N3evin** [Yeregorix/Mirage#18] opened 2019-02-10 09:39 UTC
My server crash everytime I generate a new chunk. It works fine without mirage, then it crashes again when I add mirage.

https://gist.github.com/N3evin/650f71435a92f6d9e11892b73ede21c2

**Comment by Yeregorix** [comment] 2019-02-13 18:16
I'm investigating on the issue but I see nothing related to Mirage in your crash report so it's difficult to identify the problem. Can you send me your complete logs ?

**Comment by N3evin** [comment] 2019-02-13 21:57
I guess I saw the cause. It was not compatiable with Adamantine Shield as they log. Since I am using it logged my world data.

https://forums.spongepowered.org/t/adamantineshield-v0-4-1-action-logging-and-rollback-for-sponge/20679

```
java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-2) has been closed.

at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:81)

at com.karanumcoding.adamantineshield.db.Database.getConnection(Database.java:55)

at com.karanumcoding.adamantineshield.db.DatabaseWriterTask.run(DatabaseWriterTask.java:19)

at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139)

at org.spongepowered.api.scheduler.Task$Builder$$Lambda$397.00000000A8638B50.accept(Unknown Source)

at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:192)

at org.spongepowered.common.scheduler.SchedulerBase$$Lambda$651.0000000094007180.run(Unknown Source)

at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

at java.util.concurrent.FutureTask.run(FutureTask.java:266)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

at java.lang.Thread.run(Thread.java:813)
```

java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-2) has been closed.

at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:81)

at com.karanumcoding.adamantineshield.db.Database.getConnection(Database.java:55)

at com.karanumcoding.adamantineshield.db.DatabaseWriterTask.run(DatabaseWriterTask.java:19)

at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139)

at org.spongepowered.api.scheduler.Task$Builder$$Lambda$397.00000000A8638B50.accept(Unknown Source)

at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:192)

at org.spongepowered.common.scheduler.SchedulerBase$$Lambda$651.0000000094007180.run(Unknown Source)

at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

at java.util.concurrent.FutureTask.run(FutureTask.java:266)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

at java.lang.Thread.run(Thread.java:813)

**Comment by N3evin** [comment] 2019-02-13 22:05
This the whole complete logs.

https://pastebin.com/UTJ85KAT

**Comment by Yeregorix** [comment] 2019-02-24 14:07
I'm still unable to reproduce your issue. Can you send me an archive containing a server with the minimal setup to reproduce your issue ?

**Comment by Yeregorix** [comment] 2019-06-02 19:20
I close this issue since I have no news from you. Feel free to reopen it if the issue persists with the latest version.

**Closed by Yeregorix** 2019-06-02 19:20 UTC
