### ISSUE TITLE
Phase tracking error causes the server to crash

### ISSUE THREAD

**Issue by treyzania** [Yeregorix/Mirage#2] opened 2018-05-15 22:20 UTC
I'm fairly sure that this is only happening when I have this plugin installed.  I'm using a version built from source `ec97ade`.  I was previously using the version published on Ore and was getting similar state issues.

Gist: https://gist.github.com/treyzania/6227f2c74e627d912be33a0c644400ef
And another crash log too big for gist (scroll to the end): https://tr3y.io/media/2018-05-15-7.log

I'm also getting a lot of "can't keep up" warnings that only happen with this plugin.  I'm running this on a reasonably powerful DigitalOcean droplet so I don't think that I'm actually underprovisioning the server.  I'm trying to run the timings to check to be sure if this is actually the case.

This is in the log but I'll copy it here for ease of reference:

```
Minecraft: 1.12.2
SpongeAPI: 7.1.0-SNAPSHOT-7d8a9382
SpongeVanilla: 1.12.2-7.1.0-BETA-42
```

**Comment by treyzania** [comment] 2018-05-17 13:45
Here's a zip that *should* reproduce the issue, using the 1.2.7. release: https://tr3y.io/media/antixray-example.zip

You can start the server with `harness.sh`.  I also included the `crash-reports` folder from Sponge, which has some crash logs from when I was initially testing the server, so the ones you would be looking for would be the more recent ones.

**Comment by Yeregorix** [comment] 2018-05-26 20:28
About your crash, I did not found anything related to my plugin for now, these kind of crashes are very generics and can be caused by almost anything. Keep me informed if this crash reappear.
About your performances issues, try to run some timings (10 minutes are usually enough but longer is better) and then post the timings link here or in private.
Can you also give me a copy of your worlds configurations ?

**Comment by Yeregorix** [comment] 2018-07-03 09:31
This issue was probably fixed during the numerous modifications of the last version. I close this issue as long as it does not reappear.

**Closed by Yeregorix** 2018-07-03 09:31 UTC
