### ISSUE TITLE
Mirage causes server to crash. Sponge RC3713. Exception in server tick loop

### ISSUE THREAD

**Issue by Trnrr** [Yeregorix/Mirage#22] opened 2019-05-21 01:57 UTC
Hey is this something caused by mirage or something else? I just updated my test server from 3616 to spongeforge-1.12.2-2825-7.1.6-RC3713.jar and it crashes on startup. The reason I ask here is because I see mirage in the log file at the top error. But it might be the cofh world. If mirage isn't the problem, could you shoot me in the right direction if you have any idea on what is? Thanks!

Server log: https://gist.github.com/Trnrr/5fb3de06017a8dfad0dc79cf903836a8
Crash log: https://gist.github.com/Trnrr/56384df974d768e91603892be6f78031

**Comment by Trnrr** [comment] 2019-05-21 02:02
I just tested some more and it is caused by mirage. When I remove mirage from my mods folder the server starts fine.

**Comment by Yeregorix** [comment] 2019-05-21 16:38
Duplicate of #19. I already have the fix, I will publish a new version soon.

**Closed by Yeregorix** 2019-05-21 16:38 UTC
