### ISSUE TITLE
CCL error popping up on client

### ISSUE THREAD

**Issue by nacjm** [Yeregorix/Mirage#41] opened 2020-06-04 05:26 UTC
I am getting this error in my world ever since I added mirage:
net.minecraft.util.ReportedException: Tesselating block in world
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderBlock(BlockRendererDispatcher.java:95) ~[bvm.class:?]
	at codechicken.lib.render.block.CCBlockRendererDispatcher.renderBlock(CCBlockRendererDispatcher.java:82) [CCBlockRendererDispatcher.class:?]
	at mrtjp.projectred.relocation.MovingBlockRenderDispatcher.renderBlock(renders.scala:277) [MovingBlockRenderDispatcher.class:?]
	at com.elytradev.architecture.client.render.CustomBlockDispatcher.renderBlock(CustomBlockDispatcher.java:98) [CustomBlockDispatcher.class:?]
	at gcewing.sg.BaseAORenderingManager$CustomBlockRendererDispatcher.renderBlock(BaseAORenderingManager.java:85) [BaseAORenderingManager$CustomBlockRendererDispatcher.class:?]
	at net.minecraft.client.renderer.chunk.RenderChunk.rebuildChunk(RenderChunk.java:200) [bxr.class:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.processTask(SourceFile:100) [bxn.class:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43) [bxn.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.NullPointerException
	at net.minecraft.block.BlockShulkerBox.getBlockFaceShape(SourceFile:345) ~[atr.class:?]
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.getBlockFaceShape(BlockStateContainer.java:491) ~[awu$a.class:?]
	at net.minecraft.client.renderer.BlockFluidRenderer.renderFluid(BlockFluidRenderer.java:189) ~[bvn.class:?]
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderBlock(BlockRendererDispatcher.java:84) ~[bvm.class:?]
	... 8 more
Any idea what would be causing it?

**Comment by Yeregorix** [comment] 2020-06-04 14:02
Mirage should only be installed on the server and it looks like you're using it on client. If that is the case, just remove it. Otherwise please provide full logs using a pastebin like site.

**Comment by nacjm** [comment] 2020-06-04 14:09
its only on server. What side do you want logs from?

**Comment by Yeregorix** [comment] 2020-06-04 14:55
If you have an error on the server then I need server logs. If you only have an error on the client then it's very unlikely caused by Mirage.

**Comment by nacjm** [comment] 2020-06-05 02:48
while I can understand that deduction the problem disappeared entirely once I removed mirage from the server. So clearly there is something going on.

**Comment by Yeregorix** [comment] 2020-06-05 10:32
I said that it's very unlikely caused by Mirage but I didn't said that's impossible :) In this case, give me both logs and indicate me how to reproduce the error: the mod pack used, specific things etc.

**Comment by Yeregorix** [comment] 2020-09-12 13:20
As there is no update since 3 months on this issue I'm closing it but feel free to reopen if the error reappear and you can provide logs.

**Closed by Yeregorix** 2020-09-12 13:20 UTC
