### ISSUE TITLE
NPE when entering The Twilight Forest

### ISSUE THREAD

**Issue by Anytinz** [Yeregorix/Mirage#37] opened 2020-03-21 09:15 UTC
Entering the world created by "The Twilight Forest" will cause the server to crash. Disabling Mirage will not happen.
[crash-2020-03-21_16.54.09-server.txt](https://github.com/Yeregorix/Mirage/files/4362624/crash-2020-03-21_16.54.09-server.txt)

**Comment by Yeregorix** [comment] 2020-03-21 16:38
Thanks for reporting the issue. I will investigate to find the cause of the problem.

**Comment by Yeregorix** [comment] 2020-03-27 20:49
Your issue has been fixed in the latest version.

**Closed by Yeregorix** 2020-03-27 20:49 UTC
